//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConganxaEntities : DbContext
    {
        public ConganxaEntities()
            : base("name=ConganxaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Account> tbl_Account { get; set; }
        public virtual DbSet<tbl_DoMat> tbl_DoMat { get; set; }
        public virtual DbSet<tbl_LoaiVB> tbl_LoaiVB { get; set; }
        public virtual DbSet<tbl_NguoiNhan> tbl_NguoiNhan { get; set; }
        public virtual DbSet<tbl_Tacgia> tbl_Tacgia { get; set; }
        public virtual DbSet<tbl_thongtin> tbl_thongtin { get; set; }
    
        public virtual int AccountChangePass(Nullable<int> id, string password)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AccountChangePass", idParameter, passwordParameter);
        }
    
        public virtual ObjectResult<AccountLogin_Result> AccountLogin(string userName, string password, Nullable<bool> status)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccountLogin_Result>("AccountLogin", userNameParameter, passwordParameter, statusParameter);
        }
    
        public virtual int DeleteAccount(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAccount", idParameter);
        }
    
        public virtual int DeleteDoMat(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteDoMat", iDParameter);
        }
    
        public virtual int DeleteLoaiVB(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLoaiVB", iDParameter);
        }
    
        public virtual int DeleteNguoiNhan(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteNguoiNhan", iDParameter);
        }
    
        public virtual int DeleteTacGia(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTacGia", iDParameter);
        }
    
        public virtual int DeleteThongtin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteThongtin", idParameter);
        }
    
        public virtual ObjectResult<GetAllAccount_Result> GetAllAccount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAccount_Result>("GetAllAccount");
        }
    
        public virtual ObjectResult<GetAllDomat_Result> GetAllDomat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDomat_Result>("GetAllDomat");
        }
    
        public virtual ObjectResult<GetAllLoaiVB_Result> GetAllLoaiVB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllLoaiVB_Result>("GetAllLoaiVB");
        }
    
        public virtual ObjectResult<GetAllNguoiNhan_Result> GetAllNguoiNhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllNguoiNhan_Result>("GetAllNguoiNhan");
        }
    
        public virtual ObjectResult<GetAllTacgia_Result> GetAllTacgia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTacgia_Result>("GetAllTacgia");
        }
    
        public virtual int InsertAccount(string fullName, string userName, string password, string roles, Nullable<bool> status)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var rolesParameter = roles != null ?
                new ObjectParameter("Roles", roles) :
                new ObjectParameter("Roles", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAccount", fullNameParameter, userNameParameter, passwordParameter, rolesParameter, statusParameter);
        }
    
        public virtual int InsertDoMat(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertDoMat", nameParameter);
        }
    
        public virtual int InsertLoaiVB(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLoaiVB", nameParameter);
        }
    
        public virtual int InsertNguoiNhan(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertNguoiNhan", nameParameter);
        }
    
        public virtual int InsertTacGia(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTacGia", nameParameter);
        }
    
        public virtual int InsertThongtin(string status, Nullable<System.DateTime> ngayden, string soDen, string tentacgia, string sokyhieu, Nullable<System.DateTime> ngaythang, string tenLoaiVB, string kyHieu, string tenDoMat, string nguoiNhan, Nullable<System.DateTime> ngaydukienhoanthanh, string trichyeunoidung, string ghichu, Nullable<System.DateTime> ngayHoanThanh, Nullable<bool> hoanthanh, Nullable<bool> chuahoanthanh, string vBlienket, string dinhkemfile, Nullable<System.DateTime> ngaytaoVB, string nguoithaotacuoicung)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var ngaydenParameter = ngayden.HasValue ?
                new ObjectParameter("Ngayden", ngayden) :
                new ObjectParameter("Ngayden", typeof(System.DateTime));
    
            var soDenParameter = soDen != null ?
                new ObjectParameter("SoDen", soDen) :
                new ObjectParameter("SoDen", typeof(string));
    
            var tentacgiaParameter = tentacgia != null ?
                new ObjectParameter("Tentacgia", tentacgia) :
                new ObjectParameter("Tentacgia", typeof(string));
    
            var sokyhieuParameter = sokyhieu != null ?
                new ObjectParameter("Sokyhieu", sokyhieu) :
                new ObjectParameter("Sokyhieu", typeof(string));
    
            var ngaythangParameter = ngaythang.HasValue ?
                new ObjectParameter("Ngaythang", ngaythang) :
                new ObjectParameter("Ngaythang", typeof(System.DateTime));
    
            var tenLoaiVBParameter = tenLoaiVB != null ?
                new ObjectParameter("TenLoaiVB", tenLoaiVB) :
                new ObjectParameter("TenLoaiVB", typeof(string));
    
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var tenDoMatParameter = tenDoMat != null ?
                new ObjectParameter("TenDoMat", tenDoMat) :
                new ObjectParameter("TenDoMat", typeof(string));
    
            var nguoiNhanParameter = nguoiNhan != null ?
                new ObjectParameter("NguoiNhan", nguoiNhan) :
                new ObjectParameter("NguoiNhan", typeof(string));
    
            var ngaydukienhoanthanhParameter = ngaydukienhoanthanh.HasValue ?
                new ObjectParameter("Ngaydukienhoanthanh", ngaydukienhoanthanh) :
                new ObjectParameter("Ngaydukienhoanthanh", typeof(System.DateTime));
    
            var trichyeunoidungParameter = trichyeunoidung != null ?
                new ObjectParameter("Trichyeunoidung", trichyeunoidung) :
                new ObjectParameter("Trichyeunoidung", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("Ghichu", ghichu) :
                new ObjectParameter("Ghichu", typeof(string));
    
            var ngayHoanThanhParameter = ngayHoanThanh.HasValue ?
                new ObjectParameter("NgayHoanThanh", ngayHoanThanh) :
                new ObjectParameter("NgayHoanThanh", typeof(System.DateTime));
    
            var hoanthanhParameter = hoanthanh.HasValue ?
                new ObjectParameter("Hoanthanh", hoanthanh) :
                new ObjectParameter("Hoanthanh", typeof(bool));
    
            var chuahoanthanhParameter = chuahoanthanh.HasValue ?
                new ObjectParameter("Chuahoanthanh", chuahoanthanh) :
                new ObjectParameter("Chuahoanthanh", typeof(bool));
    
            var vBlienketParameter = vBlienket != null ?
                new ObjectParameter("VBlienket", vBlienket) :
                new ObjectParameter("VBlienket", typeof(string));
    
            var dinhkemfileParameter = dinhkemfile != null ?
                new ObjectParameter("Dinhkemfile", dinhkemfile) :
                new ObjectParameter("Dinhkemfile", typeof(string));
    
            var ngaytaoVBParameter = ngaytaoVB.HasValue ?
                new ObjectParameter("NgaytaoVB", ngaytaoVB) :
                new ObjectParameter("NgaytaoVB", typeof(System.DateTime));
    
            var nguoithaotacuoicungParameter = nguoithaotacuoicung != null ?
                new ObjectParameter("Nguoithaotacuoicung", nguoithaotacuoicung) :
                new ObjectParameter("Nguoithaotacuoicung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertThongtin", statusParameter, ngaydenParameter, soDenParameter, tentacgiaParameter, sokyhieuParameter, ngaythangParameter, tenLoaiVBParameter, kyHieuParameter, tenDoMatParameter, nguoiNhanParameter, ngaydukienhoanthanhParameter, trichyeunoidungParameter, ghichuParameter, ngayHoanThanhParameter, hoanthanhParameter, chuahoanthanhParameter, vBlienketParameter, dinhkemfileParameter, ngaytaoVBParameter, nguoithaotacuoicungParameter);
        }
    
        public virtual int UpdateAccount(Nullable<int> id, string fullName, string userName, string password, string roles, Nullable<bool> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var rolesParameter = roles != null ?
                new ObjectParameter("Roles", roles) :
                new ObjectParameter("Roles", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAccount", idParameter, fullNameParameter, userNameParameter, passwordParameter, rolesParameter, statusParameter);
        }
    
        public virtual int UpdateDoMat(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDoMat", idParameter, nameParameter);
        }
    
        public virtual int UpdateLoaiVB(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLoaiVB", idParameter, nameParameter);
        }
    
        public virtual int UpdateNguoiNHan(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateNguoiNHan", idParameter, nameParameter);
        }
    
        public virtual int UpdateTacGia(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTacGia", idParameter, nameParameter);
        }
    
        public virtual int UpdateThongtin(Nullable<int> iD, string status, Nullable<System.DateTime> ngayden, string soDen, string tentacgia, string sokyhieu, Nullable<System.DateTime> ngaythang, string tenLoaiVB, string kyHieu, string tenDoMat, string nguoiNhan, Nullable<System.DateTime> ngaydukienhoanthanh, string trichyeunoidung, string ghichu, Nullable<System.DateTime> ngayHoanThanh, Nullable<bool> hoanthanh, Nullable<bool> chuahoanthanh, string vBlienket, string dinhkemfile, Nullable<System.DateTime> ngaysuaVB, string nguoithaotacuoicung)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var ngaydenParameter = ngayden.HasValue ?
                new ObjectParameter("Ngayden", ngayden) :
                new ObjectParameter("Ngayden", typeof(System.DateTime));
    
            var soDenParameter = soDen != null ?
                new ObjectParameter("SoDen", soDen) :
                new ObjectParameter("SoDen", typeof(string));
    
            var tentacgiaParameter = tentacgia != null ?
                new ObjectParameter("Tentacgia", tentacgia) :
                new ObjectParameter("Tentacgia", typeof(string));
    
            var sokyhieuParameter = sokyhieu != null ?
                new ObjectParameter("Sokyhieu", sokyhieu) :
                new ObjectParameter("Sokyhieu", typeof(string));
    
            var ngaythangParameter = ngaythang.HasValue ?
                new ObjectParameter("Ngaythang", ngaythang) :
                new ObjectParameter("Ngaythang", typeof(System.DateTime));
    
            var tenLoaiVBParameter = tenLoaiVB != null ?
                new ObjectParameter("TenLoaiVB", tenLoaiVB) :
                new ObjectParameter("TenLoaiVB", typeof(string));
    
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var tenDoMatParameter = tenDoMat != null ?
                new ObjectParameter("TenDoMat", tenDoMat) :
                new ObjectParameter("TenDoMat", typeof(string));
    
            var nguoiNhanParameter = nguoiNhan != null ?
                new ObjectParameter("NguoiNhan", nguoiNhan) :
                new ObjectParameter("NguoiNhan", typeof(string));
    
            var ngaydukienhoanthanhParameter = ngaydukienhoanthanh.HasValue ?
                new ObjectParameter("Ngaydukienhoanthanh", ngaydukienhoanthanh) :
                new ObjectParameter("Ngaydukienhoanthanh", typeof(System.DateTime));
    
            var trichyeunoidungParameter = trichyeunoidung != null ?
                new ObjectParameter("Trichyeunoidung", trichyeunoidung) :
                new ObjectParameter("Trichyeunoidung", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("Ghichu", ghichu) :
                new ObjectParameter("Ghichu", typeof(string));
    
            var ngayHoanThanhParameter = ngayHoanThanh.HasValue ?
                new ObjectParameter("NgayHoanThanh", ngayHoanThanh) :
                new ObjectParameter("NgayHoanThanh", typeof(System.DateTime));
    
            var hoanthanhParameter = hoanthanh.HasValue ?
                new ObjectParameter("Hoanthanh", hoanthanh) :
                new ObjectParameter("Hoanthanh", typeof(bool));
    
            var chuahoanthanhParameter = chuahoanthanh.HasValue ?
                new ObjectParameter("Chuahoanthanh", chuahoanthanh) :
                new ObjectParameter("Chuahoanthanh", typeof(bool));
    
            var vBlienketParameter = vBlienket != null ?
                new ObjectParameter("VBlienket", vBlienket) :
                new ObjectParameter("VBlienket", typeof(string));
    
            var dinhkemfileParameter = dinhkemfile != null ?
                new ObjectParameter("Dinhkemfile", dinhkemfile) :
                new ObjectParameter("Dinhkemfile", typeof(string));
    
            var ngaysuaVBParameter = ngaysuaVB.HasValue ?
                new ObjectParameter("NgaysuaVB", ngaysuaVB) :
                new ObjectParameter("NgaysuaVB", typeof(System.DateTime));
    
            var nguoithaotacuoicungParameter = nguoithaotacuoicung != null ?
                new ObjectParameter("Nguoithaotacuoicung", nguoithaotacuoicung) :
                new ObjectParameter("Nguoithaotacuoicung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateThongtin", iDParameter, statusParameter, ngaydenParameter, soDenParameter, tentacgiaParameter, sokyhieuParameter, ngaythangParameter, tenLoaiVBParameter, kyHieuParameter, tenDoMatParameter, nguoiNhanParameter, ngaydukienhoanthanhParameter, trichyeunoidungParameter, ghichuParameter, ngayHoanThanhParameter, hoanthanhParameter, chuahoanthanhParameter, vBlienketParameter, dinhkemfileParameter, ngaysuaVBParameter, nguoithaotacuoicungParameter);
        }
    
        public virtual ObjectResult<GetAllThongtin_Result> GetAllThongtin(Nullable<int> years)
        {
            var yearsParameter = years.HasValue ?
                new ObjectParameter("Years", years) :
                new ObjectParameter("Years", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllThongtin_Result>("GetAllThongtin", yearsParameter);
        }
    }
}
